package it.airgap.tezos.core.coder.encoded

import it.airgap.tezos.core.internal.annotation.InternalTezosSdkApi

@InternalTezosSdkApi
public interface EncodedCoderContext :
    AddressCoderContext,
    ImplicitAddressCoderContext,
    BlockHashCoderContext,
    BlockMetadataHashCoderContext,
    BlockPayloadHashCoderContext,
    ChainIdCoderContext,
    ContextHashCoderContext,
    ContractHashCoderContext,
    CryptoboxPublicKeyHashCoderContext,
    Ed25519BlindedPublicKeyHashCoderContext,
    Ed25519EncryptedSeedCoderContext,
    Ed25519PublicKeyCoderContext,
    Ed25519PublicKeyHashCoderContext,
    Ed25519SecretKeyCoderContext,
    Ed25519SeedCoderContext,
    Ed25519SignatureCoderContext,
    GenericSignatureCoderContext,
    NonceHashCoderContext,
    OperationHashCoderContext,
    OperationListHashCoderContext,
    OperationListListHashCoderContext,
    OperationMetadataHashCoderContext,
    OperationMetadataListHashCoderContext,
    OperationMetadataListListHashCoderContext,
    P256EncryptedSecretKeyCoderContext,
    P256PublicKeyCoderContext,
    P256PublicKeyHashCoderContext,
    P256SecretKeyCoderContext,
    P256SignatureCoderContext,
    ProtocolHashCoderContext,
    PublicKeyCoderContext,
    SaplingAddressCoderContext,
    SaplingSpendingKeyCoderContext,
    ScriptExprHashCoderContext,
    Secp256K1ElementCoderContext,
    Secp256K1EncryptedScalarCoderContext,
    Secp256K1EncryptedSecretKeyCoderContext,
    Secp256K1PublicKeyCoderContext,
    Secp256K1PublicKeyHashCoderContext,
    Secp256K1ScalarCoderContext,
    Secp256K1SecretKeyCoderContext,
    Secp256K1SignatureCoderContext,
    SignatureCoderContext